version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/conf.d/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./docker/mysql/log:/var/log/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db1234

volumes:
  db-data: